from . import loan_type
from . import loan_loan
from . import loan_installment
from . import loan_payment
from . import loan_disbursement
from . import loan_payment_register
from . import loan_disburse_wizard
from . import loan_foreclose_wizard
from . import loan_collection_report_wizard
