{
    "name": "Loan Management System",
    "version": "19.0.6.0.0",
    "summary": "End-to-end customer loan lifecycle management",
    "category": "Accounting/Accounting",
    "author": "Custom",
    "website": "https://example.com",
    "license": "LGPL-3",
    "depends": ["mail", "account", "website", "portal"],
    "data": [
        "security/loan_security.xml",
        "security/ir.model.access.csv",
        "data/loan_sequence.xml",
        "views/loan_type_views.xml",
        "views/loan_views.xml",
        "views/loan_installment_views.xml",
        "views/loan_payment_views.xml",
        "views/loan_disbursement_views.xml",
        "views/loan_payment_register_views.xml",
        "views/loan_disburse_wizard_views.xml",
        "views/loan_foreclose_wizard_views.xml",
        "views/loan_collection_report_wizard_views.xml",
        "report/loan_agreement_report.xml",
        "report/loan_operational_reports.xml",
        "views/loan_menus.xml",
        "views/website/loan_portal_templates.xml",
    ],
    "application": True,
    "installable": True,
}
